name: Patch and Build
on: [ push, pull_request ]
jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
      - name: Initialize Git submodules
        run: git submodule update --init --recursive
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Configure Git user details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Apply patches
        run: ./gradlew applyPatches
      - name: Build Paperclip
        run: ./gradlew paperclip
      - name: Upload Paperclip
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: '*-paperclip.jar'
